- name: GitHub Releases to Discord
  uses: SethCohen/github-releases-to-discord@v1
  with:
    webhook_url: ${{ secrets.WEBHOOK_URL }}
    username: "Release Changelog"
    color: "2105893"
    footer_title: "Changelog"
    reduce_headings: true
    include_body: true

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: GitHub Releases to Discord
        uses: SethCohen/github-releases-to-discord@v1
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          color: "2105893"
          username: "Release Changelog"
          avatar_url: "https://cdn.discordapp.com/embed/avatars/0.png"
          content: "||@everyone||"
          footer_title: "Changelog"
          reduce_headings: true
